const data = {
  user: {},
  tasks: [
    {
      id: "1",
      title: "Составить список",
      description: "Составить список",
      list: "Задачи",
      isFocus: false,
      isImportant: false,
      isFast: false,
      color: "red",
      tags: ["Программирование", "Работа", "Маркетинг"],
      cluster: "false",
      startDate: "2024-10-4",
      startTime: "12:00",
      alert: "",
      children: ["2", "3", "4"],
      isCompleted: false,
      emodji: "🔥",
      type: "task",
      background:
        "https://avatars.dzeninfra.ru/get-zen_doc/10768392/pub_6508876a3129ee5d90d52f3a_65088dfd88601d1945309167/scale_1200",
      expand: false,
    },
    {
      id: "2",
      title: "Написать приложение",
      description: "Составить список",
      list: "Маркетинг",
      isFocus: false,
      isImportant: false,
      isFast: false,
      color: "blue",
      tags: ["Проверка"],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: [],
      isCompleted: true,
      emodji: "",
      type: "task",
      parent: "1",
      background: "",
      expand: false,
    },
    {
      id: "3",
      title:
        "Протестировать приложение для работы на работе, чтобы было в нем все мега прекрасно",
      description: "",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: [],
      isCompleted: false,
      emodji: "",
      type: "task",
      parent: "1",
      background: "",
      expand: false,
    },
    {
      id: "4",
      title: "Вложенная",
      description: "Составить список",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: ["17"],
      isCompleted: false,
      emodji: "",
      type: "task",
      parent: "1",
      background: "",
      expand: false,
    },
    {
      id: "5",
      title: "Новая",
      description: "Составить список",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: ["6"],
      isCompleted: false,
      emodji: "",
      type: "Идея",
      background: "",
      expand: false,
    },
    {
      id: "6",
      title: "Внутренняя",
      description: "Составить список",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: [],
      isCompleted: false,
      emodji: "",
      type: "Идея",
      parent: "5",
      background: "",
      expand: false,
    },
    {
      id: "17",
      title: "ВЛ2",
      description: "Составить список",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: ["18"],
      isCompleted: false,
      emodji: "",
      type: "task",
      parent: "4",
      background: "",
      expand: false,
    },
    {
      id: "18",
      title: "ВЛ3",
      description: "Составить список",
      list: "Любовь",
      isFocus: false,
      isImportant: true,
      isFast: false,
      color: "blue",
      tags: [],
      cluster: "false",
      startDate: "",
      startTime: "",
      alert: "",
      children: [],
      isCompleted: false,
      emodji: "",
      type: "task",
      parent: "17",
      background: "",
      expand: false,
    },
  ],
  categories: [
    {
      color: "red",
      name: "Красная",
    },
    {
      color: "green",
      name: "Зеленая",
    },
    {
      color: "blue",
      name: "Синяя",
    },
    {
      color: "yellow",
      name: "Желтая",
    },
    {
      color: "purple",
      name: "Фиолетовая",
    },
    {
      color: "orange",
      name: "Оранжевая",
    },
    {
      color: "pink",
      name: "Розовая",
    },
    {
      color: "gray",
      name: "Серая",
    },
    {
      color: "black",
      name: "Черная",
    },
    {
      color: "white",
      name: "Белая",
    },
    {
      color: "brown",
      name: "Коричневая",
    },
    {
      color: "cyan",
      name: "Голубая",
    },
    {
      color: "magenta",
      name: "Маджента",
    },
    {
      color: "lime",
      name: "Лаймовая",
    },
    {
      color: "teal",
      name: "Бирюзовая",
    },
    {
      color: "maroon",
      name: "Бордовая",
    },
    {
      color: "navy",
      name: "Темно-синяя",
    },
    {
      color: "olive",
      name: "Оливковая",
    },
    {
      color: "silver",
      name: "Серебряная",
    },
    {
      color: "gold",
      name: "Золотая",
    },
    {
      color: "indigo",
      name: "Индиго",
    },
    {
      color: "violet",
      name: "Лиловая",
    },
    {
      color: "beige",
      name: "Бежевая",
    },
  ],
  tags: {
    Работа: false,
    Любовь: false,
    Маркетинг: false,
    Финансы: false,
    Программирование: false,
  },
};

export default data;
